services:
  postgres:
    image: ${PG_APP}
    container_name: postgresql
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    env_file: .env
    ports:
      - ${PG_PORT}:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    env_file: .env
    ports:
      - ${PGADMIN_PORT}:80
volumes:
  db-volume:
    name: pg-data
